/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.App
import org.example.app.Fecha

fun main() {
    println(App().greeting)
    val fecha = Fecha(2025, "Mayo", 29)
    fecha.mostrar()
}